name: msu_connect
description: A comprehensive portal for Midlands State University students.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  #google_classroom: ^0.2.0
  flutter_animate: ^4.5.0
  loading_animation_widget: ^1.2.0+4
  webview_flutter: ^4.0.0
  image_picker: ^1.0.0
  path_provider: ^2.0.11
  permission_handler: ^12.0.0+1
  google_sign_in: ^6.0.0
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/